name: Workflow Actions with Manual Trigger

on:
  workflow_dispatch:

jobs:
  actions-job:
    runs-on: ubuntu-latest
    steps:
      - name: Actions Checkout Code using GitHub Action
        uses: actions/checkout@v4.2.2 # This GitHub Action is used to get the code
        with:
            repository: ${{ github.repository }}
            ref: ${{ github.ref }}
      - name: Run Action
        run: echo "This workflow was triggered manually. Running actions for ${{ github.repository }}"