name: Deploy via SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
        #   SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          scp -P "$SERVER_PORT" frontend/index.html "$SERVER_USER@$SERVER_IP:/home/$SERVER_USER/public_html/index.html"
          echo "Deployment completed successfully!" | ssh -p "$SERVER_PORT" "$SERVER_USER@$SERVER_IP" "cat > /home/$SERVER_USER/public_html/deployment.log"
          echo "Deployment log created on the server."
          echo "Deployment to $SERVER_USER@$SERVER_IP completed successfully!"