name: Workflow jobs manual trigger

on:
  workflow_dispatch:

jobs:
  manual-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step-for-job1
        run: "echo Job 1: ${{ github.job }} workflow triggered manually."

  manual-job2:
    runs-on: ubuntu-latest
    needs: manual-job1
    steps:
      - name: Step-for-job2
        run: "echo Job 2: ${{ github.job }} workflow triggered manually."

  manual-job3:
    runs-on: ubuntu-latest
    needs: manual-job1
    steps:
      - name: Step-for-job3
        run: "echo Job 3: ${{ github.job }} workflow triggered manually."

  manual-job4:
    runs-on: ubuntu-latest
    needs: [manual-job2, manual-job3]
    steps:
      - name: Step-for-job4
        run: "echo Job 4: ${{ github.job }} workflow triggered manually."