name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  examble-job:
    runs-on: ubuntu-latest

    steps:
      - name : Print a welcome message
        run: echo "Welcome to our first GitHub Actions Workflow :)"

      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: List repository files
        run: ls -la

      - name: Print commit information
        run: |
          echo "This commit was made by ${{ github.actor }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Time: ${{ github.event.head_commit.timestamp }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"