name: Manual-trigger-workflow

on:
  workflow_dispatch:

jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: Manual-trigger-step
        run: echo "This workflow was triggered manually."